name: peminjam_perpustakaan_kelas_b
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  font_awesome_flutter: ^10.6.0
  flutter_onboarding_slider: ^1.0.11
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  auto_size_text: ^3.0.0
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^4.2.1
  circular_profile_avatar: ^2.0.5
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  material_floating_search_bar_2: ^0.5.0
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  lottie: ^3.0.0
  get_storage: 2.0.3
  fluttertoast: ^8.2.4
  flutter_pw_validator: ^1.6.0
  intl: 0.19.0
  get: 4.6.5
  email_validator: '^2.1.16'
  url_launcher: ^6.0.8
  flutter_svg: ^2.0.10+1
  flutter: 
    sdk: flutter
  art_sweetalert: ^0.0.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

#flutter:
#  assets:
#    - assets/images/
#
#  uses-material-design: true
#
#
#
#  fonts:
#    - family: Poopins
#      fonts:
#        - asset: assets/fonts/Poppins-Bold.ttf
#        - asset: assets/fonts/Poppins-Italic.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#        - asset: assets/fonts/Poppins-Regular.ttf

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/buku/
    - assets/kategoriBuku/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf